# Generated by Django 5.2.17 on 2026-08-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('device_category', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('verdict', models.CharField(choices=[('GENUINE', 'Genuine'), ('REVOKED', 'Revoked'), ('NOT_FOUND', 'Not found')], max_length=16)),
                ('product', models.ForeignKey(blank=True, help_text='Null when the scanned code matched no product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='products.product')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['product', 'scanned_at'], name='verificatio_product_3f37bb_idx')],
            },
        ),
    ]
