# Generated by Django 5.2.17 on 2026-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
