# Generated by Django 5.2.17 on 2026-08-12 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COMPANY_SUBMITTED', 'Company application submitted'), ('COMPANY_RESUBMITTED', 'Company application resubmitted'), ('COMPANY_APPROVED', 'Company approved'), ('COMPANY_REJECTED', 'Company rejected'), ('COMPANY_SUSPENDED', 'Company suspended'), ('COMPANY_REACTIVATED', 'Company reactivated'), ('PRODUCT_REGISTERED', 'Product registered'), ('PRODUCT_REVOKED', 'Product revoked')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__e2abcf_idx')],
            },
        ),
    ]
