# Generated by Django 5.2.17 on 2026-08-12 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='entry_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='previous_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('COMPANY_SUBMITTED', 'Company application submitted'), ('COMPANY_RESUBMITTED', 'Company application resubmitted'), ('COMPANY_APPROVED', 'Company approved'), ('COMPANY_REJECTED', 'Company rejected'), ('COMPANY_SUSPENDED', 'Company suspended'), ('COMPANY_REACTIVATED', 'Company reactivated'), ('PRODUCT_REGISTERED', 'Product registered'), ('PRODUCT_REVOKED', 'Product revoked'), ('CUSTODY_ACCEPTED', 'Custody transfer accepted'), ('CUSTODY_DECLINED', 'Custody transfer declined')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
