# Generated by Django 5.2.17 on 2026-08-12 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('COMMERCIAL', 'Commercial company'), ('ARTISAN', 'Artisan workshop')], max_length=16)),
                ('verification_track', models.CharField(choices=[('CHAMBER_OF_COMMERCE', 'Chamber of Commerce'), ('OFFICIAL_REGISTRY', 'Official registry'), ('ARTISAN_REVIEW', 'Manual artisan review')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=16)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='company-logos/')),
                ('registry_code', models.CharField(blank=True, help_text='Official registry code. Required for a commercial company (FR08).', max_length=64)),
                ('status_reason', models.TextField(blank=True, help_text='Why the application was rejected or the company suspended (DBR12).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-submitted_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('company_type', 'COMMERCIAL'), ('verification_track__in', ['CHAMBER_OF_COMMERCE', 'OFFICIAL_REGISTRY'])), models.Q(('company_type', 'ARTISAN'), ('verification_track', 'ARTISAN_REVIEW')), _connector='OR'), name='company_track_matches_type'), models.CheckConstraint(condition=models.Q(models.Q(('company_type', 'COMMERCIAL'), models.Q(('registry_code', ''), _negated=True)), models.Q(('company_type', 'ARTISAN'), ('registry_code', '')), _connector='OR'), name='commercial_company_has_registry_code'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('REJECTED', 'SUSPENDED')), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='negative_decision_states_a_reason')],
            },
        ),
    ]
