# Generated by Django 5.2.17 on 2026-08-12 01:00

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_code', models.CharField(db_index=True, default=products.models.generate_passport_code, max_length=64, unique=True)),
                ('product_type', models.CharField(choices=[('COMMERCIAL_ORIGINAL', 'Commercial original'), ('ARTISAN', 'Artisan')], max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('origin', models.CharField(help_text='Place of manufacture.', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='product-images/')),
                ('integrity_hash', models.CharField(blank=True, max_length=64)),
                ('revocation_reason', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companies.company')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='INITIATED', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers', to='products.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVOKED'), _negated=True), models.Q(('revocation_reason', ''), _negated=True), _connector='OR'), name='revocation_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='custodytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_holder', models.F('to_holder')), _negated=True), name='custody_transfer_changes_holder'),
        ),
    ]
