# Generated by Django 5.2.17 on 2026-09-10 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sign_existing_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custodytransfer',
            constraint=models.UniqueConstraint(fields=('product', 'previous_hash'), name='custody_transfer_links_to_one_predecessor'),
        ),
    ]
