# Generated by Django 5.2.17 on 2026-10-01 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sprint3_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytransfer',
            name='transfer_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
