# Generated by Django 5.2.17 on 2026-10-01 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_transfer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custodytransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'INITIATED')), fields=('product',), name='custody_transfer_one_open_offer'),
        ),
    ]
